# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DN MRSHLL RNGG
email: donixo@live.com
description: > # this means to ignore newlines until "baseurl:"
  <i>/ doni-marshall-rangga /</i>. Tulisan dalam bahasa Indonesia, dalam bentuk ejaan yang belum tentu baik dan benar. Dibuat untuk menampung review serta catatan teknis pemrograman perangkat lunak penulis. Terkadang juga memuat omelan, misuhan dan yang lainnya. Yang termuat di sini adalah murni pendapat pribadi penulis, bukan merupakan pandangan institusi tempat penulis bekerja.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://donixo.github.io" # the base hostname & protocol for your site
twitter_username: donixo
github_username:  donixo

# Build settings
markdown: kramdown
